# Generated by Django 4.2.1 on 2023-07-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_slider_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Title',
            new_name='title',
        ),
    ]
