# Generated by Django 4.2.1 on 2023-07-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_title_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.TextField(),
        ),
    ]
